apiVersion: kubeadm.k8s.io/v1beta3
bootstrapTokens:
- groups:
  - system:bootstrappers:kubeadm:default-node-token
  token: abcdef.1234567890abcdef
  ttl: 24h0m0s
  usages:
  - signing
  - authentication
kind: InitConfiguration
localAPIEndpoint:
  advertiseAddress: 10.100.100.100
  bindPort: 6443
nodeRegistration:
  criSocket: /run/containerd/containerd.sock
  imagePullPolicy: IfNotPresent
  name: node-001.local
  taints:
  - effect: NoSchedule
    key: node-role.kubernetes.io/master
---
apiServer:
  timeoutForControlPlane: 4m0s
apiVersion: kubeadm.k8s.io/v1beta3
certificatesDir: /etc/kubernetes/pki
clusterName: kubernetes
controlPlaneEndpoint: 10.100.100.100:6443
controllerManager: {}
dns: {}
etcd:
  external:
    caFile: /etc/kubernetes/pki/etcd/ca.pem
    certFile: /etc/kubernetes/pki/etcd/etcd.pem
    endpoints:
    - https://10.100.100.100:2379
    - https://10.100.100.100:2379
    - https://10.100.100.100:2379
    keyFile: /etc/kubernetes/pki/etcd/etcd-key.pem
imageRepository: node-001.local/kubernetes
kind: ClusterConfiguration
kubernetesVersion: v1.28.11
networking:
  dnsDomain: cluster.local
  podSubnet: 192.168.100.100/20
  serviceSubnet: 10.96.0.0/12
scheduler: {}
                                              
